[project]
name = 'project'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.marketplace-storage]
path = 'contracts/marketplace-storage.clar'

[contracts.marketplace-trait]
path = 'contracts/marketplace-trait.clar'

[contracts.nft-marketplace]
path = 'contracts/nft-marketplace.clar'
depends_on = ['marketplace-trait', 'marketplace-storage']

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"

[contracts.sip009-nft]
path = "contracts/sip009-nft.clar"
depends_on =["sip009-nft-trait"]

[contracts.sip010-token]
path = "contracts/sip010-token.clar"
depends_on =["sip010-ft-trait"]

clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
